package com.s2p.practice.hackerrank.challenges.morganString;

// https://www.hackerrank.com/challenges/morgan-and-a-string/problem

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

public class Solution {

    // Complete the morganAndString function below.
    static String morganAndString(String a, String b) {
        if (a == null || a.length() == 0) {
            return b;
        }

        if (b == null || b.length() == 0) {
            return a;
        }

        int i = 0, j = 0;

        char aChar, bChar;

        StringBuilder result = new StringBuilder();

        while (i < a.length() && j < b.length()) {

            aChar = a.charAt(i);
            bChar = b.charAt(j);

            if (aChar < bChar) {
                result.append(aChar);
                i++;
            } else if (bChar < aChar) {
                result.append(bChar);
                j++;
            } else {
                Object[] helper = evaluateTie(a, b, i, j);
                String offset = (String) helper[0];

                i = (int) helper[1];
                j = (int) helper[2];

                result.append(offset);

                /*if (i + 1 < a.length() && j + 1 < b.length()) {
                    if (a.charAt(i + 1) < b.charAt(j + 1)) {
                        result.append(aChar);
                        i++;
                    } else {
                        result.append(bChar);
                        j++;
                    }
                }*/
            }
        }

        for (; i < a.length(); i++) {
            result.append(a.charAt(i));
        }

        for (; j < b.length(); j++) {
            result.append(b.charAt(j));
        }

        return result.toString();
    }

    private static Object[] evaluateTie(String a, String b, int i, int j) {
        StringBuilder result = new StringBuilder();

        char aChar = a.charAt(i);
        char bChar = b.charAt(j);

        /*if (i + 1 >= a.length() && j + 1 >= b.length()) {
            return new Object[]{"" + sameChar + "" + sameChar, i + 1, j + 1};
        }

        if (i + 1 >= a.length()) {
            return new Object[]{"" + sameChar, i, j + 1};
        }

        if (j + 1 >= b.length()) {
            return new Object[]{"" + sameChar, i + 1, j};
        }*/

        int startI = i, startJ = j;

        while (true) {
            if (i >= a.length()) {
                return new Object[]{"" + a.charAt(startI), startI + 1, startJ};
            }

            if (j >= a.length()) {
                return new Object[]{"" + a.charAt(startJ), startI, startJ + 1};
            }

            if (a.charAt(i) == b.charAt(j)) {
                result.append(a.charAt(i));
                i++;
                j++;
                continue;
            }

            if (a.charAt(i) < b.charAt(i)) {
                return new Object[]{"" + a.charAt(startI), startI + 1, startJ};
            }

            if (a.charAt(i) > b.charAt(i)) {
                return new Object[]{"" + a.charAt(startJ), startI, startJ + 1};
            }
        }
    }

    private static final Scanner scanner = new Scanner(System.in);

    public static void main_1(String[] args) throws IOException {
        BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter("/Users/naveen/Projects/hackerrank/src/com/s2p/problems/hackerrank/challenges/morganString/output.txt"));

        int t = scanner.nextInt();
        scanner.skip("(\r\n|[\n\r\u2028\u2029\u0085])?");

        for (int tItr = 0; tItr < t; tItr++) {
            String a = scanner.nextLine();

            String b = scanner.nextLine();

            String result = morganAndString(a, b);

            bufferedWriter.write(result);
            bufferedWriter.newLine();
        }

        bufferedWriter.close();

        scanner.close();
    }

    public static void main(String[] args) {
        System.out.println(morganAndString("JACK", "DANIEL"));
        System.out.println(morganAndString("ABACABA", "ABACABA"));


        String a = "YZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZY";
        String b = "ZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZY";
        System.out.println(morganAndString(a, b));
    }
}
